name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-2022 # Ortamı sabitle

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Doctor (log için)
        run: flutter doctor -v

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      # *** KRİTİK: Bozuk build artifaktlarını ve ephemeral'ı temizle ***
      - name: Clean + remove build artifacts
        shell: pwsh
        run: |
          flutter clean
          Remove-Item -Recurse -Force build, .dart_tool -ErrorAction SilentlyContinue
          if (Test-Path "windows/flutter/ephemeral") { Remove-Item -Recurse -Force "windows/flutter/ephemeral" }
      
      # *** KRİTİK: Windows engine dosyalarını önceden indir (flutter_windows.dll buradan gelir) ***
      - name: Precache Windows engine
        run: flutter precache --windows

      # Windows klasörü yoksa oluştur; varsa dokunma (yeniden yazdırma karmaşa yaratabiliyor)
      - name: Ensure Windows runner exists
        shell: pwsh
        run: |
          if (!(Test-Path "windows/CMakeLists.txt")) {
            flutter create --platforms=windows .
          }
      
      - name: Pub get
        run: flutter pub get

      # (İsteğe bağlı) NBSP temizliği — kopyala/yapıştır hatalarını önler
      - name: Normalize non-breaking spaces in Dart files
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Filter *.dart | ForEach-Object {
            $t = Get-Content $_.FullName -Raw
            $t = $t -replace [char]0x00A0, ' ' -replace [char]0x200B, ''
            Set-Content -Path $_.FullName -Value $t -Encoding UTF8
          }

      # --- Giriş dosyası --target ile açıkça belirtildi ---
      - name: Build Windows (release)
        run: flutter build windows --release --target=lib/main.dart -v

      - name: Zip release folder
        shell: pwsh
        run: |
          $p1 = "build/windows/x64/runner/Release"
          $p2 = "build/windows/runner/Release"
          $src = (Test-Path $p1) ? $p1 : $p2
          if (!(Test-Path $src)) { throw "Release folder not found" }
          Compress-Archive -Path "$src/*" -DestinationPath "Biscornue-Windows.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Biscornue-Windows
          path: Biscornue-Windows.zip
          if-no-files-found: error
