name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Ensure Windows runner exists
        run: flutter create --platforms=windows .

      - name: Pub get
        run: flutter pub get

      - name: Build Windows (release)
        run: flutter build windows --release

      - name: Zip release folder
        shell: pwsh
        run: |
          $src = "build/windows/x64/runner/Release"
          Compress-Archive -Path "$src/*" -DestinationPath "Biscornue-Windows.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Biscornue-Windows
          path: Biscornue-Windows.zip
          if-no-files-found: error
